<a href="https://colab.research.google.com/github/BaberFaisal/Pandas_Practice/blob/main/Pandas__Pratice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
import pandas as pd

data = {
    'EmployeeID': [101, 102, 103, 104, 105, 106],
    'Name': ['Faisal', 'Sara', 'Ali', 'Zainab', 'Bilal', 'Hina'],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR', 'Finance'],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female'],
    'Age': [25, 28, 24, 30, None, 27],
    'Salary': [70000, 80000, 72000, 90000, 78000, None],
    'JoiningDate': [
        '2022-05-15', '2021-11-01', '2023-01-10',
        '2020-08-24', '2022-12-01', '2021-03-15'
    ],
    'City': ['Karachi', 'Lahore', 'Karachi', 'Islamabad', 'Lahore', 'Islamabad'],
    'PerformanceScore': [8.5, 9.2, 7.8, 8.9, 9.0, 8.1],
    'Bonus': [5000, 6000, 4000, 8000, 5500, 7000]
}

df = pd.DataFrame(data)

In [4]:
df

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus
0,101,Faisal,IT,Male,25.0,70000.0,2022-05-15,Karachi,8.5,5000
1,102,Sara,HR,Female,28.0,80000.0,2021-11-01,Lahore,9.2,6000
2,103,Ali,IT,Male,24.0,72000.0,2023-01-10,Karachi,7.8,4000
3,104,Zainab,Finance,Female,30.0,90000.0,2020-08-24,Islamabad,8.9,8000
4,105,Bilal,HR,Male,NaN,78000.0,2022-12-01,Lahore,9.0,5500
5,106,Hina,Finance,Female,27.0,NaN,2021-03-15,Islamabad,8.1,7000

In [6]:
df.tail(3)

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus
3,104,Zainab,Finance,Female,30.0,90000.0,2020-08-24,Islamabad,8.9,8000
4,105,Bilal,HR,Male,NaN,78000.0,2022-12-01,Lahore,9.0,5500
5,106,Hina,Finance,Female,27.0,NaN,2021-03-15,Islamabad,8.1,7000

In [10]:
df.shape

(6, 10)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EmployeeID        6 non-null      int64
 1   Name              6 non-null      object
 2   Department        6 non-null      object
 3   Gender            6 non-null      object
 4   Age               5 non-null      float64
 5   Salary            5 non-null      float64
 6   JoiningDate       6 non-null      object
 7   City              6 non-null      object
 8   PerformanceScore  6 non-null      float64
 9   Bonus             6 non-null      int64
dtypes: float64(3), int64(2), object(5)
memory usage: 612.0+ bytes

In [12]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [13]:
df.describe()

       EmployeeID        Age        Salary  PerformanceScore        Bonus
count    6.000000   5.000000      5.000000          6.000000     6.000000
mean   103.500000  26.800000  78000.000000          8.583333  5916.666667
std      1.870829   2.387467   7874.007874          0.549242  1428.869017
min    101.000000  24.000000  70000.000000          7.800000  4000.000000
25%    102.250000  25.000000  72000.000000          8.200000  5125.000000
50%    103.500000  27.000000  78000.000000          8.700000  5750.000000
75%    104.750000  28.000000  80000.000000          8.975000  6750.000000
max    106.000000  30.000000  90000.000000          9.200000  8000.000000

In [18]:
# multiple columns
df[["Name", "Salary"]]

     Name   Salary
0  Faisal  70000.0
1    Sara  80000.0
2     Ali  72000.0
3  Zainab  90000.0
4   Bilal  78000.0
5    Hina      NaN

In [19]:
# select rows
df.iloc[0]

EmployeeID                 101
Name                    Faisal
Department                  IT
Gender                    Male
Age                       25.0
Salary                 70000.0
JoiningDate         2022-05-15
City                   Karachi
PerformanceScore           8.5
Bonus                     5000
Name: 0, dtype: object

In [25]:
df.iloc[0:2]

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus
0,101,Faisal,IT,Male,25.0,70000.0,2022-05-15,Karachi,8.5,5000
1,102,Sara,HR,Female,28.0,80000.0,2021-11-01,Lahore,9.2,6000

In [22]:
df.iloc[0:3:2]

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus
0,101,Faisal,IT,Male,25.0,70000.0,2022-05-15,Karachi,8.5,5000
2,103,Ali,IT,Male,24.0,72000.0,2023-01-10,Karachi,7.8,4000

In [23]:
#Using loc by label
df.loc[0]

EmployeeID                 101
Name                    Faisal
Department                  IT
Gender                    Male
Age                       25.0
Salary                 70000.0
JoiningDate         2022-05-15
City                   Karachi
PerformanceScore           8.5
Bonus                     5000
Name: 0, dtype: object

In [24]:
df.loc[0:2] #(inclusive)

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus
0,101,Faisal,IT,Male,25.0,70000.0,2022-05-15,Karachi,8.5,5000
1,102,Sara,HR,Female,28.0,80000.0,2021-11-01,Lahore,9.2,6000
2,103,Ali,IT,Male,24.0,72000.0,2023-01-10,Karachi,7.8,4000

In [26]:
#select both rows and columns
df.loc[0, "Name"]

'Faisal'

In [27]:
df.loc[0:1, "Name"]

0    Faisal
1      Sara
Name: Name, dtype: object

In [29]:
df.loc[0:1, ["Name","Age"]]

     Name   Age
0  Faisal  25.0
1    Sara  28.0

In [30]:
df[df["Age"]> 23]

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus
0,101,Faisal,IT,Male,25.0,70000.0,2022-05-15,Karachi,8.5,5000
1,102,Sara,HR,Female,28.0,80000.0,2021-11-01,Lahore,9.2,6000
2,103,Ali,IT,Male,24.0,72000.0,2023-01-10,Karachi,7.8,4000
3,104,Zainab,Finance,Female,30.0,90000.0,2020-08-24,Islamabad,8.9,8000
5,106,Hina,Finance,Female,27.0,NaN,2021-03-15,Islamabad,8.1,7000

In [31]:
df[df["Name"] == "Faisal"]

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus
0,101,Faisal,IT,Male,25.0,70000.0,2022-05-15,Karachi,8.5,5000

In [36]:
df[(df["Age"]>29) & (df["Salary"] > 8000)]

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus
3,104,Zainab,Finance,Female,30.0,90000.0,2020-08-24,Islamabad,8.9,8000

In [34]:
# isin() for Membership
df[df["Name"].isin(["Faisal", "Sara"])]

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus
0,101,Faisal,IT,Male,25.0,70000.0,2022-05-15,Karachi,8.5,5000
1,102,Sara,HR,Female,28.0,80000.0,2021-11-01,Lahore,9.2,6000

In [39]:
# Query
df.query("Age > 23 and Name == 'Faisal'") # careful

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus
0,101,Faisal,IT,Male,25.0,70000.0,2022-05-15,Karachi,8.5,5000

In [40]:
# .at and .iat (Fast Accessors)
#df.at[row_label, column_label]
#df.iat[row_index, column_index]

df.at[0, "Name"]

'Faisal'

In [41]:
df.iat[0,1]

'Faisal'

In [42]:
# Null
df.isnull()

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,True,False,False,False,False,False
5,False,False,False,False,False,True,False,False,False,False

In [43]:
df.isnull().sum()

EmployeeID          0
Name                0
Department          0
Gender              0
Age                 1
Salary              1
JoiningDate         0
City                0
PerformanceScore    0
Bonus               0
dtype: int64

In [44]:
df.notnull()

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus
0,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,False,True,True,True,True,True
5,True,True,True,True,True,False,True,True,True,True

In [46]:
# Drop
df.dropna() # drop rows with any missing values
df.dropna(axis=1) # drop columns with any missing values

,EmployeeID,Name,Department,Gender,JoiningDate,City,PerformanceScore,Bonus
0,101,Faisal,IT,Male,2022-05-15,Karachi,8.5,5000
1,102,Sara,HR,Female,2021-11-01,Lahore,9.2,6000
2,103,Ali,IT,Male,2023-01-10,Karachi,7.8,4000
3,104,Zainab,Finance,Female,2020-08-24,Islamabad,8.9,8000
4,105,Bilal,HR,Male,2022-12-01,Lahore,9.0,5500
5,106,Hina,Finance,Female,2021-03-15,Islamabad,8.1,7000

In [48]:
# Drop
df.dropna(how="all") # drop rows where all values are missing

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus
0,101,Faisal,IT,Male,25.0,70000.0,2022-05-15,Karachi,8.5,5000
1,102,Sara,HR,Female,28.0,80000.0,2021-11-01,Lahore,9.2,6000
2,103,Ali,IT,Male,24.0,72000.0,2023-01-10,Karachi,7.8,4000
3,104,Zainab,Finance,Female,30.0,90000.0,2020-08-24,Islamabad,8.9,8000
4,105,Bilal,HR,Male,NaN,78000.0,2022-12-01,Lahore,9.0,5500
5,106,Hina,Finance,Female,27.0,NaN,2021-03-15,Islamabad,8.1,7000

In [50]:
# Drop rows if a specific column is missing
df.dropna(subset=["Salary"])

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus
0,101,Faisal,IT,Male,25.0,70000.0,2022-05-15,Karachi,8.5,5000
1,102,Sara,HR,Female,28.0,80000.0,2021-11-01,Lahore,9.2,6000
2,103,Ali,IT,Male,24.0,72000.0,2023-01-10,Karachi,7.8,4000
3,104,Zainab,Finance,Female,30.0,90000.0,2020-08-24,Islamabad,8.9,8000
4,105,Bilal,HR,Male,NaN,78000.0,2022-12-01,Lahore,9.0,5500

In [52]:
# Filling Missing Values
df.fillna(0)

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus
0,101,Faisal,IT,Male,25.0,70000.0,2022-05-15,Karachi,8.5,5000
1,102,Sara,HR,Female,28.0,80000.0,2021-11-01,Lahore,9.2,6000
2,103,Ali,IT,Male,24.0,72000.0,2023-01-10,Karachi,7.8,4000
3,104,Zainab,Finance,Female,30.0,90000.0,2020-08-24,Islamabad,8.9,8000
4,105,Bilal,HR,Male,0.0,78000.0,2022-12-01,Lahore,9.0,5500
5,106,Hina,Finance,Female,27.0,0.0,2021-03-15,Islamabad,8.1,7000

In [53]:
df.fillna("Unknown")

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus
0,101,Faisal,IT,Male,25.0,70000.0,2022-05-15,Karachi,8.5,5000
1,102,Sara,HR,Female,28.0,80000.0,2021-11-01,Lahore,9.2,6000
2,103,Ali,IT,Male,24.0,72000.0,2023-01-10,Karachi,7.8,4000
3,104,Zainab,Finance,Female,30.0,90000.0,2020-08-24,Islamabad,8.9,8000
4,105,Bilal,HR,Male,Unknown,78000.0,2022-12-01,Lahore,9.0,5500
5,106,Hina,Finance,Female,27.0,Unknown,2021-03-15,Islamabad,8.1,7000

In [55]:
df["Salary"].fillna(df["Salary"].mean())

0    70000.0
1    80000.0
2    72000.0
3    90000.0
4    78000.0
5    78000.0
Name: Salary, dtype: float64

In [57]:
#Replacing Values
df.replace("N/A", None)

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus
0,101,Faisal,IT,Male,25.0,70000.0,2022-05-15,Karachi,8.5,5000
1,102,Sara,HR,Female,28.0,80000.0,2021-11-01,Lahore,9.2,6000
2,103,Ali,IT,Male,24.0,72000.0,2023-01-10,Karachi,7.8,4000
3,104,Zainab,Finance,Female,30.0,90000.0,2020-08-24,Islamabad,8.9,8000
4,105,Bilal,HR,Male,NaN,78000.0,2022-12-01,Lahore,9.0,5500
5,106,Hina,Finance,Female,27.0,NaN,2021-03-15,Islamabad,8.1,7000

In [59]:
df["Gender"].replace({'Male':'M', 'Female': 'F'})

0    M
1    F
2    M
3    F
4    M
5    F
Name: Gender, dtype: object

In [61]:
# Rename Columns
df.rename(columns = {"old":"new"} )

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus
0,101,Faisal,IT,Male,25.0,70000.0,2022-05-15,Karachi,8.5,5000
1,102,Sara,HR,Female,28.0,80000.0,2021-11-01,Lahore,9.2,6000
2,103,Ali,IT,Male,24.0,72000.0,2023-01-10,Karachi,7.8,4000
3,104,Zainab,Finance,Female,30.0,90000.0,2020-08-24,Islamabad,8.9,8000
4,105,Bilal,HR,Male,NaN,78000.0,2022-12-01,Lahore,9.0,5500
5,106,Hina,Finance,Female,27.0,NaN,2021-03-15,Islamabad,8.1,7000

In [62]:
df.columns = [col.lower() for col in df.columns] # see the structure

In [63]:
df

,employeeid,name,department,gender,age,salary,joiningdate,city,performancescore,bonus
0,101,Faisal,IT,Male,25.0,70000.0,2022-05-15,Karachi,8.5,5000
1,102,Sara,HR,Female,28.0,80000.0,2021-11-01,Lahore,9.2,6000
2,103,Ali,IT,Male,24.0,72000.0,2023-01-10,Karachi,7.8,4000
3,104,Zainab,Finance,Female,30.0,90000.0,2020-08-24,Islamabad,8.9,8000
4,105,Bilal,HR,Male,NaN,78000.0,2022-12-01,Lahore,9.0,5500
5,106,Hina,Finance,Female,27.0,NaN,2021-03-15,Islamabad,8.1,7000

In [64]:
# Remove duplicates
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [65]:
df.drop_duplicates()

,employeeid,name,department,gender,age,salary,joiningdate,city,performancescore,bonus
0,101,Faisal,IT,Male,25.0,70000.0,2022-05-15,Karachi,8.5,5000
1,102,Sara,HR,Female,28.0,80000.0,2021-11-01,Lahore,9.2,6000
2,103,Ali,IT,Male,24.0,72000.0,2023-01-10,Karachi,7.8,4000
3,104,Zainab,Finance,Female,30.0,90000.0,2020-08-24,Islamabad,8.9,8000
4,105,Bilal,HR,Male,NaN,78000.0,2022-12-01,Lahore,9.0,5500
5,106,Hina,Finance,Female,27.0,NaN,2021-03-15,Islamabad,8.1,7000

In [68]:
# Convert Data Types
df["bonus"] = df["bonus"].astype(int)

In [69]:
df["Date"] = pd.to_datetime(df["Date"])

In [7]:
# sort by columnn values
df.sort_values(by = "Salary", ascending = False )

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus
3,104,Zainab,Finance,Female,30.0,90000.0,2020-08-24,Islamabad,8.9,8000
1,102,Sara,HR,Female,28.0,80000.0,2021-11-01,Lahore,9.2,6000
4,105,Bilal,HR,Male,NaN,78000.0,2022-12-01,Lahore,9.0,5500
2,103,Ali,IT,Male,24.0,72000.0,2023-01-10,Karachi,7.8,4000
0,101,Faisal,IT,Male,25.0,70000.0,2022-05-15,Karachi,8.5,5000
5,106,Hina,Finance,Female,27.0,NaN,2021-03-15,Islamabad,8.1,7000

In [9]:
# sort multiole columns
df.sort_values(by = ["Salary", "Bonus"])

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus
0,101,Faisal,IT,Male,25.0,70000.0,2022-05-15,Karachi,8.5,5000
2,103,Ali,IT,Male,24.0,72000.0,2023-01-10,Karachi,7.8,4000
4,105,Bilal,HR,Male,NaN,78000.0,2022-12-01,Lahore,9.0,5500
1,102,Sara,HR,Female,28.0,80000.0,2021-11-01,Lahore,9.2,6000
3,104,Zainab,Finance,Female,30.0,90000.0,2020-08-24,Islamabad,8.9,8000
5,106,Hina,Finance,Female,27.0,NaN,2021-03-15,Islamabad,8.1,7000

In [11]:
# sort by index
df.sort_index()

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus
0,101,Faisal,IT,Male,25.0,70000.0,2022-05-15,Karachi,8.5,5000
1,102,Sara,HR,Female,28.0,80000.0,2021-11-01,Lahore,9.2,6000
2,103,Ali,IT,Male,24.0,72000.0,2023-01-10,Karachi,7.8,4000
3,104,Zainab,Finance,Female,30.0,90000.0,2020-08-24,Islamabad,8.9,8000
4,105,Bilal,HR,Male,NaN,78000.0,2022-12-01,Lahore,9.0,5500
5,106,Hina,Finance,Female,27.0,NaN,2021-03-15,Islamabad,8.1,7000

In [13]:
# setting and resetting index
df.set_index("EmployeeID")

,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus
EmployeeID,,,,,,,,,
101,Faisal,IT,Male,25.0,70000.0,2022-05-15,Karachi,8.5,5000
102,Sara,HR,Female,28.0,80000.0,2021-11-01,Lahore,9.2,6000
103,Ali,IT,Male,24.0,72000.0,2023-01-10,Karachi,7.8,4000
104,Zainab,Finance,Female,30.0,90000.0,2020-08-24,Islamabad,8.9,8000
105,Bilal,HR,Male,NaN,78000.0,2022-12-01,Lahore,9.0,5500
106,Hina,Finance,Female,27.0,NaN,2021-03-15,Islamabad,8.1,7000

In [16]:
df.reset_index(inplace = True)

In [17]:
df

,index,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus
0,0,101,Faisal,IT,Male,25.0,70000.0,2022-05-15,Karachi,8.5,5000
1,1,102,Sara,HR,Female,28.0,80000.0,2021-11-01,Lahore,9.2,6000
2,2,103,Ali,IT,Male,24.0,72000.0,2023-01-10,Karachi,7.8,4000
3,3,104,Zainab,Finance,Female,30.0,90000.0,2020-08-24,Islamabad,8.9,8000
4,4,105,Bilal,HR,Male,NaN,78000.0,2022-12-01,Lahore,9.0,5500
5,5,106,Hina,Finance,Female,27.0,NaN,2021-03-15,Islamabad,8.1,7000

In [20]:
df = df.drop(columns = ["index"])

In [21]:
df

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus
0,101,Faisal,IT,Male,25.0,70000.0,2022-05-15,Karachi,8.5,5000
1,102,Sara,HR,Female,28.0,80000.0,2021-11-01,Lahore,9.2,6000
2,103,Ali,IT,Male,24.0,72000.0,2023-01-10,Karachi,7.8,4000
3,104,Zainab,Finance,Female,30.0,90000.0,2020-08-24,Islamabad,8.9,8000
4,105,Bilal,HR,Male,NaN,78000.0,2022-12-01,Lahore,9.0,5500
5,106,Hina,Finance,Female,27.0,NaN,2021-03-15,Islamabad,8.1,7000

In [23]:
# Basic Maths
df["total"] = df["Salary"] + df["Bonus"]

In [24]:
df

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus,total
0,101,Faisal,IT,Male,25.0,70000.0,2022-05-15,Karachi,8.5,5000,75000.0
1,102,Sara,HR,Female,28.0,80000.0,2021-11-01,Lahore,9.2,6000,86000.0
2,103,Ali,IT,Male,24.0,72000.0,2023-01-10,Karachi,7.8,4000,76000.0
3,104,Zainab,Finance,Female,30.0,90000.0,2020-08-24,Islamabad,8.9,8000,98000.0
4,105,Bilal,HR,Male,NaN,78000.0,2022-12-01,Lahore,9.0,5500,83500.0
5,106,Hina,Finance,Female,27.0,NaN,2021-03-15,Islamabad,8.1,7000,NaN

In [25]:
# Applying custom functions
df["Name Length"] = df["Name"].apply(len)

In [26]:
df

,EmployeeID,Name,Department,Gender,Age,Salary,JoiningDate,City,PerformanceScore,Bonus,total,Name Length
0,101,Faisal,IT,Male,25.0,70000.0,2022-05-15,Karachi,8.5,5000,75000.0,6
1,102,Sara,HR,Female,28.0,80000.0,2021-11-01,Lahore,9.2,6000,86000.0,4
2,103,Ali,IT,Male,24.0,72000.0,2023-01-10,Karachi,7.8,4000,76000.0,3
3,104,Zainab,Finance,Female,30.0,90000.0,2020-08-24,Islamabad,8.9,8000,98000.0,6
4,105,Bilal,HR,Male,NaN,78000.0,2022-12-01,Lahore,9.0,5500,83500.0,5
5,106,Hina,Finance,Female,27.0,NaN,2021-03-15,Islamabad,8.1,7000,NaN,4

In [29]:
# column wise summary
df.mean(numeric_only=True) # important numeric_only=True

EmployeeID            103.500000
Age                    26.800000
Salary              78000.000000
PerformanceScore        8.583333
Bonus                5916.666667
total               83700.000000
Name Length             4.666667
dtype: float64

In [31]:
df["Age"].std()

2.3874672772626644

In [35]:
# count values
df["Department"].value_counts() # important

Department
IT         2
HR         2
Finance    2
Name: count, dtype: int64

In [36]:
df["City"].unique()

array(['Karachi', 'Lahore', 'Islamabad'], dtype=object)

In [37]:
df["City"].nunique()

3

In [39]:
# goup by
# what is average salary by department
df.groupby("Department")["Salary"].mean()

Department
Finance    90000.0
HR         79000.0
IT         71000.0
Name: Salary, dtype: float64

In [41]:
df.groupby(["Department", "Gender"])["Salary"].mean()

Department  Gender
Finance     Female    90000.0
HR          Female    80000.0
            Male      78000.0
IT          Male      71000.0
Name: Salary, dtype: float64

In [42]:
"""
AGGREGATION FUNCTIONS
Function	Purpose
mean()	Average
sum()	Total
count()	Number of entries
min() / max()	Min / Max
std()	Standard deviation
agg()	Multiple functions

"""

'\nAGGREGATION FUNCTIONS\nFunction\tPurpose\nmean()\tAverage\nsum()\tTotal\ncount()\tNumber of entries\nmin() / max()\tMin / Max\nstd()\tStandard deviation\nagg()\tMultiple functions\n\n'

In [43]:
# Multiple Aggregations with agg()
df.groupby("Department")["Salary"].agg(["mean","max", "min"])

               mean      max      min
Department
Finance     90000.0  90000.0  90000.0
HR          79000.0  80000.0  78000.0
IT          71000.0  72000.0  70000.0

In [45]:
# count items
df["Department"].value_counts() # flat count

Department
IT         2
HR         2
Finance    2
Name: count, dtype: int64

In [47]:
df.groupby("Department").size()

Department
Finance    2
HR         2
IT         2
dtype: int64